---
micronaut:
  application:
    name: fixtures

---
mongodb:
  uri: "mongodb://${MONGO_HOST:192.168.235.131}:${MONGO_PORT:27017}"

---
consul:
  client:
    registration:
      enabled: true
    defaultZone: "${CONSUL_HOST:192.168.235.131}:${CONSUL_PORT:8500}"
