micronaut:
  application:
    name: clubs-service
  server:
    #random port
    port: -1
---
hibernate:
  hbm2ddl:
    auto: update
---
dataSource:
  url: jdbc:h2:mem:devDb;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
  pooled: true
  jmxExport: true
  driverClassName: org.h2.Driver
  username: sa
  password: ''
---
  consul:
    client:
      registration:
        enabled: true
    defaultZone: "${CONSUL_HOST:localhost}:${CONSUL_PORT:8500}"
